git submodule add https://github.com/mileszs/ack.vim.git ./bundle/ack
git submodule add https://github.com/scrooloose/nerdtree.git ./bundle/nerdtree
git submodule add https://github.com/vim-scripts/taglist.vim.git ./bundle/taglist
git submodule add https://github.com/MarcWeber/vim-addon-mw-utils.git ./bundle/vim_addon_mw_utils
git submodule add https://github.com/wincent/command-t.git ./bundle/command
git submodule add https://github.com/vim-scripts/ReplaceWithRegister.git  ./bundle/ReplaceWithRegister
git submodule add https://github.com/tomtom/tcomment_vim.git ./bundle/tcomment_vim
git submodule add https://github.com/garbas/vim-snipmate.git ./bundle/vim_snipmate
git submodule add https://github.com/vim-scripts/LustyExplorer.git ./bundle/LustyExplorer
git submodule add https://github.com/wincent/scalpel.git ./bundle/scalpel
git submodule add https://github.com/tomtom/tlib_vim.git ./bundle/tlib_vim
git submodule add https://github.com/honza/vim-snippets.git ./bundle/vim_snippets
git submodule add https://github.com/haya14busa/incsearch.vim.git ./bundle/incsearch
